{{- if eq .Values.ingress.exist true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace : {{ .Values.global.namespace }}
  annotations:
  {{- include "ingress.annotations" . | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.canaryStrategy.root }}
                port:
                  name: use-annotation
{{- end }}